=== AlbertoSalazar05/EjerciciosLMSGI/cocteleria/cocteleria.dtd
<!ELEMENT cocteleria (coctel+)>
<!ELEMENT coctel (nombre, tipo, ingredientes, precio)>
<!ATTLIST coctel id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT ingredientes (ingrediente+, (opcion1 | opcion2)?)>
<!ELEMENT ingrediente (#PCDATA)>
<!ELEMENT opcion1 (#PCDATA)>
<!ELEMENT opcion2 (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST elemento atributo (valor1 | valor2 | valor3) #REQUIRED>

=== AlbertoSalazar05/EjerciciosLMSGI/cocteleria/cocteleria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cocteleria SYSTEM "cocteleria.dtd">
<cocteleria>
    <coctel id="a">
        <nombre>Mojito</nombre>
        <tipo>Clásico</tipo>
        <ingredientes>
            <ingrediente>Lima</ingrediente>
            <ingrediente>Menta</ingrediente>
            <ingrediente>Azúcar</ingrediente>
        </ingredientes>
        <precio>7</precio>
    </coctel>
    <coctel id="b">
        <nombre>Daquiri</nombre>
        <tipo>Clásico</tipo>
        <ingredientes>
            <ingrediente>Lima</ingrediente>
            <ingrediente>Ron</ingrediente>
            <ingrediente>Azúcar</ingrediente>
        </ingredientes>
        <precio>8</precio>
    </coctel>
    <coctel id="c">
        <nombre>Americano</nombre>
        <tipo>Clásico</tipo>
        <ingredientes>
            <ingrediente>Campari</ingrediente>
            <ingrediente>Ron</ingrediente>
            <ingrediente>Vermouth Rojo</ingrediente>
        </ingredientes>
        <precio>6</precio>
    </coctel>
</cocteleria>
